# Generated by Django 4.2.7 on 2023-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('sequence', models.PositiveIntegerField(verbose_name='순서')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('tag', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('D', 'Design'), ('QA', 'Quality Assurance'), ('PM', 'Project Manager'), ('Doc', 'Document')], max_length=10, verbose_name='태그')),
                ('sequence', models.PositiveIntegerField(verbose_name='순서')),
                ('volume', models.FloatField(verbose_name='작업량')),
                ('ended_at', models.DateField(verbose_name='마감일')),
            ],
        ),
    ]
