# Generated by Django 4.2.7 on 2023-11-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('tag', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('D', 'Design'), ('QA', 'Quality Assurance'), ('PM', 'Project Manager'), ('Doc', 'Document')], max_length=10)),
                ('sequence', models.PositiveIntegerField(verbose_name='순서')),
                ('volume', models.FloatField(verbose_name='작업량')),
                ('ended_at', models.DateField(verbose_name='마감일')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.column', verbose_name='컬럼')),
            ],
        ),
    ]
