name: EC2 CD

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2
              env:
                  PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
                  HOST_NAME: ${{ secrets.EC2_HOST }}
                  USER_NAME: ${{ secrets.EC2_USER_NAME }}
              run: |
                  echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
                    cd /home/ubuntu/project-management &&
                    git checkout main &&
                    git fetch --all &&
                    git reset --hard origin/main &&
                    git pull origin main'
