name: EC2 CD

on:
    pull_request:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }} '
                      cd /project-management &&
                      git fetch --all &&
                      git pull origin main'
